services:
  db:
    image: postgres:alpine
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-db:
