services:
  db:
    image: postgres:alpine
    env_file:
      - ./api/.env
    ports:
      - "5444:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./api/.env.docker
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - db

  # front:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./frontend/.env
  #   environment:
  #     - VITE_API_BASE_URL=${VITE_API_BASE_URL}
  #   ports:
  #     - "3333:3000"
  #   depends_on:
  #     - api

volumes:
  postgres-db:
