apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scrabble-postgres
  namespace: default
spec:
  serviceName: scrabble-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: scrabble-postgres
  template:
    metadata:
      labels:
        app: scrabble-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: scrabble-db-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: scrabble-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scrabble-db-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: scrabble-postgres-svc
  namespace: default
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: scrabble-postgres
  clusterIP: None
