name: Backend Tests

on:
  push:
    paths:
      - 'api/**'
      - 'migrations/**'
      - 'test-api.sh'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'api/**'
      - 'migrations/**'
      - 'test-api.sh'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: api/go.mod
          cache: true

      - name: Run API tests via script
        run: |
          chmod +x ./test-api.sh
          ./test-api.sh
